#include "hash_tables.h"

/**
 * key_index - returns index of a key
 * @key: key generated by djb2 algorithm
 * @size: size of hash table
 * Return: index related to a given key
 */
unsigned long int key_index(const unsigned char *key, unsigned long int size)
{
	unsigned long int int_key;
	unsigned long int index;

	int_key = hash_djb2(key);
	index = int_key % size;

	return (index);
}
